### ISSUE TITLE
When selecting a track, the wrong highlight color is used

### ISSUE THREAD

**Issue by windowsrefund** [windowsrefund/grayscale-theme#1]
Anything would be better than this strange dark highlight behavior when selecting a track. This example shows track 2 selected.

![track](https://github.com/windowsrefund/grayscale-theme/assets/512222/da3ce440-f788-47d9-8e59-06ebe1e3886e)

![mixer-strip](https://github.com/windowsrefund/grayscale-theme/assets/512222/a0e8b354-fc98-42e8-a260-0b3a300e018b)

**Comment by G3N-es** [comment]
This happens when the "MidLight" value drops below 120. I think it's a Qt (or maybe Fusion) event to guarantee the display in light or dark themes, but in practice what it does is make the display even more unpredictable. theme customization.

**Comment by windowsrefund** [comment]
Thanks for confirming "Midlight" as the culprit. I've been suspicious of him and now I know for sure. I'll keep this open in the event someone knows a fix or I get lucky.

**Comment by windowsrefund** [comment]
Closing in light of the change mentioned [here](https://www.rncbc.org/drupal/comment/10733#comment-10733)
